### ISSUE TITLE
Roadmap 2

### ISSUE THREAD

**Issue by jprivet-dev** [jprivet-dev/git-xtended#38]
## La documentation
- [x] Mettre à jour la documentation
- [ ] Insérer des pictos
- [x] Insérer des GIF de présentation
- [ ] Faire une version plus graphique du “Basic Branch-per-Issue GitHub Worflow”
- [ ] Créer une vidéo de présentation

## Les fonctionnalités

- Installation des fonctionnalités
    - [x] Améliorer l’affichage des différentes étapes
- Prompt with Git information
    - [ ] Permettre de composer le prompt comme on le souhaite
    - user.name & email, local et global
        - [x] Permettre la configuration
        - [x] Afficher ces infos dans l’aide
    - Commits behind & ahead :
        - [x] Permettre la configuration de la branche de référence (ex: origin/dev) de façon globale et locale
- Git aliases
    - [x] Permettre le paramétrages des alias
- Git hooks
    - prepare-commit-msg
        - [x] Compléter les informations
        - [x] Faire un refactoring de tout le code
        - [ ] Proposition automatique du type de commit en fonction du type du fichier ciblé
- Git workflow commands (Agility)
    - [ ] Rechercher des fonctionnalités pertinentes
- Bash aliases
- GBW commands
- Dans tout le projet
    - [ ] Remplacer les `echo` par des `printf`

## Les tests

- [ ] Compléter les tests pour couvrir plus de fonctions
- [ ] Améliorer le titre d’accueil
- [ ] Améliorer le listing des fonctions gbw_xxx ayants un test dédié test_gbw_xxx (titre + listing)
- [ ] Afficher un listing des fonctions test_gbw_yyy de test ne ciblant pas spécifiquement une fonction gbw_xxx (titre + listing). EX : vérification d’ensemble au changement d’un paramètre global
- Lancement des tests (test + listing)
    - [ ] Insérer le temps d’exécution totale du test test_gbw_xxx
    - [ ] Connaître les fonctions appelées durant un test (dans ce cas faire le listing des fonctions ayant un test après)

## Refactoring & Autres

- [ ] Utiliser `gbw_print_colors` à la place de `echo -e`
- [ ] Créer `assert count-lines`
- [x] Utiliser "\`...\`" à la place de"$(...)" (non recommandé par codacy - garder "$(...)")
- [ ] Eliminer les fonctions de type `gbw_prompt_host_colors`
